version: "3.8"
services:
  backend:
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydb?schema=public
      - JWT_HASH=ourhashing

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - db_vol:/var/lib/mysql

  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_vol:
