version: "3.8"
services:
  backend:
    image: hindiesuputra/hackathon-be
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_vol:/var/lib/mysql

  frontend:
    image: hindiesuputra/hackathon-fe
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_vol:
